use PLANETS_OOP;
SELECT PLANETS.NAMES,PLANEtS.RADIUS,PLANETS.TEMPERATURE, PLANETS.HAVE_LIFE,PLANETS.HAVE_ATMOSPHERE,SATELLITES.NAMES FROM dbo.PLANETS INNER JOIN dbo.SATELLITES 
		ON PLANETS.NAMES = SATELLITES.PLANET;


SELECT o.NAMES,[Минимальный радиус],isnull([Количество спутников],0) [Количество спутников] FROM (SELECT TOP 1 NAMES, RADIUS [Минимальный радиус] FROM PLANETS rt  order by RADIUS asc) o left outer join (SELECT SATELLITES.PLANET, count(*) [Количество спутников] from SATELLITES
group by SATELLITES.PLANET) s
		ON o.NAMES = s.PLANET;

SELECT TOP 1 rt1.NAMES,[Сумма радиусов] from (SELECT PLANETS.NAMES, sum(SATELLITES.RADIUS)[Сумма радиусов] FROM PLANETS inner JOIN SATELLITES on PLANETS.NAMES = SATELLITES.PLANET GROUP BY PLANETS.NAMES) rt1 order by [Сумма радиусов] desc;