use UNIVER;
select AUDITORIUM_TYPE.AUDITORIUM_TYPENAME, AUDITORIUM.AUDITORIUM
	from AUDITORIUM inner join AUDITORIUM_TYPE
	on AUDITORIUM_TYPE.AUDITORIUM_TYPE = AUDITORIUM.AUDITORIUM_TYPE and AUDITORIUM_TYPE.AUDITORIUM_TYPENAME like '%[ к]омпьютер%';

use UNIVER;
select PROGRESS.NOTE, STUDENT.NAME, FACULTY.FACULTY, GROUPS.PROFESSION, SUBJECT.SUBJECT, PULPIT.PULPIT, case
		when (PROGRESS.NOTE = 6) then 'six'
		when (PROGRESS.NOTE = 7) then 'seven'
		when (PROGRESS.NOTE = 8) then 'eight'
		end LiteralNotes
	from PROGRESS inner join STUDENT
		on PROGRESS.NOTE between 6 and 8 and PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
		inner join SUBJECT
		on SUBJECT.SUBJECT = PROGRESS.SUBJECT
		inner join PULPIT
		on PULPIT.PULPIT = SUBJECT.PULPIT
		inner join GROUPS
		on STUDENT.IDGROUP = GROUPS.IDGROUP
		inner join FACULTY
		on FACULTY.FACULTY = GROUPS.FACULTY

use UNIVER;
select isnull (TEACHER.TEACHER_NAME, '**') TeacherName, PULPIT.PULPIT_NAME
	from TEACHER right outer join PULPIT
		on TEACHER.PULPIT = PULPIT.PULPIT
		order by PULPIT.PULPIT_NAME
--full
use UNIVER;
select * from GROUPS full join STUDENT
	on GROUPS.IDGROUP = STUDENT.IDGROUP
	order by STUDENT.IDGROUP
	
select count(*) from GROUPS full join STUDENT
	on GROUPS.IDGROUP = STUDENT.IDGROUP
	where STUDENT.IDGROUP is null
--left
use UNIVER;
select * from GROUPS left join STUDENT
	on GROUPS.IDGROUP = STUDENT.IDGROUP
	order by STUDENT.IDGROUP
	
select count(*) from GROUPS left join STUDENT
	on GROUPS.IDGROUP = STUDENT.IDGROUP
	where STUDENT.IDGROUP is null
--right
use UNIVER;
select * from GROUPS right join STUDENT
	on GROUPS.IDGROUP = STUDENT.IDGROUP
	order by STUDENT.IDGROUP
	
select count(*) from GROUPS right join STUDENT
	on GROUPS.IDGROUP = STUDENT.IDGROUP
	where STUDENT.IDGROUP is null

use UNIVER;
select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
	from AUDITORIUM cross join AUDITORIUM_TYPE
		where AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
