//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_DBFIST
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule
    {
        public int id { get; set; }
        public System.DateTime start_time { get; set; }
        public System.DateTime end_time { get; set; }
        public string activity_type { get; set; }
        public int employee_id { get; set; }
        public Nullable<int> max_participants { get; set; }
        public Nullable<int> taken_seats { get; set; }
    
        public virtual employees employees { get; set; }
    }
}
