//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab9_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_plans
    {
        public int id { get; set; }
        public int client_id { get; set; }
        public int plan_id { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public Nullable<int> progress { get; set; }
    
        public virtual clients clients { get; set; }
        public virtual workout_plans workout_plans { get; set; }
    }
}
