//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab9_EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fitness_centerEntities : DbContext
    {
        public fitness_centerEntities()
            : base("name=fitness_centerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<client_plans> client_plans { get; set; }
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<employees> employees { get; set; }
        public virtual DbSet<schedule> schedule { get; set; }
        public virtual DbSet<workout_plans> workout_plans { get; set; }
    }
}
