//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_MOdeldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity1
    {
        public int Id { get; set; }
        public string Price { get; set; }
    }
}
